### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by danya201272** [galaxy119/SCP-575#1]
[blackout]  Exception thrown by timed job:
System.TypeLoadException: Could not resolve type with token 01000027 (from typeref, class/assembly Smod2.API.Room, Smod2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
  at scp4aiur.Timing.OnUpdate (Smod2.Events.UpdateEvent ev) [0x001e5] in <adfe77913d224a1ea9e02dde9225da44>:0

**Comment by galaxy119** [comment]
Do you have the testing version of SMOD? It's required for this plugin.

**Comment by danya201272** [comment]
No

**Comment by danya201272** [comment]
Please sent me

**Comment by galaxy119** [comment]
https://cdn.discordapp.com/attachments/499602857738371073/543586150246252544/Assembly-CSharp.dll
https://cdn.discordapp.com/attachments/499602857738371073/543586151605338113/Smod2.dll
