### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Tamago4a** [galaxy119/SCP-575#11]
Is it possible to change this text to Russian?
https://cdn.discordapp.com/attachments/547435822065123367/551841638805405697/unknown.png

**Comment by galaxy119** [comment]
If you want to translate it, feel free to fork the repo and make the translation. I don't speak russian well enough to do it.

**Comment by Tamago4a** [comment]
So I do not mind helping you with the translation into Russian. Only I do not understand. Why can't users give the opportunity to specify the text after the murder?

**Comment by galaxy119** [comment]
Because there's already a large amont of config options already, adding abunch more just for translation purposes would be extremely cumbersome and literally no other plugin does this.

**Comment by Tamago4a** [comment]
You in the discord should have been written by one of my friends. He would have thrown off the ready-made code for translation into other languages.
https://cdn.discordapp.com/attachments/569214516991361055/579685554707234836/Screenshot_7.png
https://cdn.discordapp.com/attachments/569214516991361055/579685564706586643/20190519220034_1.jpg
https://cdn.discordapp.com/attachments/569214516991361055/579685565687922721/20190519220155_1.jpg
