### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by danya201272** [galaxy119/SCP-575#6]
Dont work Tesla and 575 dont turn off light in timer

**Comment by galaxy119** [comment]
Could you explain in more detail exactly what you mean?

**Comment by danya201272** [comment]
tESLA DONT KILL

**Comment by danya201272** [comment]
tesla always time off and dont kill everyone

**Comment by danya201272** [comment]
With 575 plugin

**Comment by galaxy119** [comment]
Teslas are disabled during normal timed SCP-575 blackouts.
I'm going to add a config option to turn this feature on or off, but for now - it's intended.

If tesla's are STAYING off ALL the time, make sure your Smod is up to date (3.3.0), and provide me some kind of error or MA_output_log.txt file.
